name: AYAB Firmware

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
        eval "${MATRIX_EVAL}"
        pip install gcovr
        gcovr --version
    - name: Run Test
      run: |
        ./test/test.sh

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get install arduino-mk
    - name: Prepare
      run: |
        export ARDMK_DIR=$(dirname $(find /usr -name Arduino.mk))
        export ARDUINO_DIR=$ARDMK_DIR
    - name: Build
      run: |
        ./build.sh
        ls build
    - name: Archive
        cd build
        zip ayab-firmware.zip ./*
        pwd
        ls
