language: c
before_install:
    - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
    - sleep 3
    - export DISPLAY=:1.0
    - wget http://downloads.arduino.cc/arduino-1.0.6-linux64.tgz
    - tar xf arduino-1.0.6-linux64.tgz
    - pwd
    - ls
    - mkdir /home/travis/tools
    - mv arduino-1.0.6 /home/travis/tools/arduino-1.0.6
    - ls /home/travis/tools/
    - mkdir build
install:
script:
    - make BOARD=uno MACHINETYPE=KH910
    - mv ayab.hex build/kh910_uno_0-80.hex
    - make clean
    - make BOARD=uno MACHINETYPE=KH930
    - mv ayab.hex build/kh930_uno_0-80.hex
    - make clean
    - make BOARD=mega MACHINETYPE=KH910
    - mv ayab.hex build/kh910_mega_0-80.hex
    - make clean
    - make BOARD=mega MACHINETYPE=KH930
    - mv ayab.hex build/kh930_mega_0-80.hex
    - make clean
    - ls build
notifications:
    email:
        on_success: change
        on_failure: change
