matrix:
  include:
  - language: cpp
    dist: focal
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
    env:
    - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
    before_install:
    - eval "${MATRIX_EVAL}"
    - pip install gcovr
    - gcovr --version
    script:
    - "./test/test.sh"
  - language: c
    dist: focal
    addons:
        apt:
            packages:
            - arduino-mk
    before_install:
      - >-
        /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid
        --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0
        1280x1024x16
      - sleep 3
      - 'export DISPLAY=:1.0'
      - 'export ARDMK_DIR=$(dirname $(find /usr -name Arduino.mk))'
      - 'export ARDUINO_DIR=$ARDMK_DIR'
    install: true
    script:
      - ./build.sh
      - ls build
      - cd build
      - zip ayab-firmware.zip ./*
      - pwd
      - ls
    notifications:
      email:
        on_success: change
        on_failure: change
    deploy:
      provider: releases
      api_key:
        secure: >-
          NRuUqhUFremhUKuSGqb2FXjXmZAyeahu8rUYWuiquqfXWmW7HsYU0SCEakoGiPULvJr4j1j2UqJjZQt3x8ORnolMs0FWkbvA3tqexZN04wPMGGWUtI29CxOKOsgmcyYn2qfOu54i8q5vwUgXjiNOQEFoGkzIeyTDL4TvjwHi5gfhSpGGLJbu7NfpFKxC9mkVBztZzlpUspwDn12dYH++Rb4zGf628AUOHh6tA0SLzHVISbG1mMz5C9ORKTyfR9mZB0TZ1J/Murha1Yof9AvxcHLUBau/IPdUyk3G2nx89vi9YTpO4Wddi9ChULXJyc5dnwJj4/8uNHd1NsgoUNgYWowAA6+cHfnCyoBMnt4z/h3WEVOFvRNilw5tRz3XtnnTBnHBUwScpVyfo9bp5QsJ4AHXHsEy/s3w/8fZCEDA8jRtnb9rj0u6SHDjSBDjJx/haPPNtv6+ZlmUUQ84kmlKY2u8SGI4HA8a/MJpe3EhtfDbezkmPBNd08n3UID0nIWk80nCJ9McVMHdjkgsXo3xlO5fRiqlI+OMe62gCQ7EwVopViCPNOTrfiIXasafeoL0M0xkwAGvuCRdke6WbkA79HS5QkgKCEFkZBD6f+t/Vd6S38KKpAbPwAWOF30UmiMI6VZbQv8mrr2Lr8/qxN4rcsU84353EhBRUf3WYeoshGI=
      file: '${HOME}/build/${TRAVIS_REPO_SLUG}/build/ayab-firmware.zip'
      skip_cleanup: true
      'on':
        tags: true
