AYAB Arduino Firmware: Fsm Class Reference
Fsm Class Reference
Public Member Functions
void init () final
Initialize Finite State Machine.
OpState_t getState () final
Get machine state.
void setState (OpState_t state) final
Set machine state.
void dispatch () final
Dispatch on machine state.
Private Member Functions
void state_wait_for_machine () const
Action of machine in state wait_for_machine.
void state_init ()
Action of machine in state OpState::init.
void state_ready () const
Action of machine in state OpState::ready.
void state_knit () const
Action of machine in state OpState::knit.
void state_test () const
Action of machine in state OpState::test.
void state_error ()
Action of machine in state OpState::error.
Private Attributes
OpState_t m_currentState
OpState_t m_nextState
Err_t m_error
bool m_flash
unsigned long m_flashTime
Member Function Documentation
dispatch()
void Fsm::dispatch () final virtual
Dispatch on machine state.
Implements FsmInterface.
References state_error(), state_init(), state_knit(), state_ready(), state_test(), and state_wait_for_machine().
getState()
OpState_t Fsm::getState () final virtual
Get machine state.
Returns
Current state of Finite State Machine.
Implements FsmInterface.
init()
void Fsm::init () final virtual
Initialize Finite State Machine.
Implements FsmInterface.
setState()
void Fsm::setState (OpState_t state) final virtual
Set machine state.
Parameters
state State.
Does not take effect until next dispatch()
Implements FsmInterface.
The documentation for this class was generated from the following files:
src/ayab/fsm.h
src/ayab/fsm.cpp
test/mocks/fsm_mock.cpp