AYAB Arduino Firmware: Tester Class Reference
Tester Class Reference
Public Member Functions
Err_t startTest (Machine_t machineType) final
Start hardware test.
void loop () final
Main loop for hardware tests.
void helpCmd () final
Help command handler.
void sendCmd () final
Send command handler.
void beepCmd () final
Beep command handler.
void setSingleCmd (const uint8_t *buffer, size_t size) final
Set single solenoid command handler.
void setAllCmd (const uint8_t *buffer, size_t size) final
Set all solenoids command handler.
void readEOLsensorsCmd () final
Read EOL sensors command handler.
void readEncodersCmd () final
Read encoders command handler.
void autoReadCmd () final
Auto read command handler.
void autoTestCmd () final
Auto test command handler.
void stopCmd () final
Stop command handler.
void quitCmd () final
Quit command handler.
void encoderChange () final
Interrupt service routine for encoder A.
Private Member Functions
void setUp ()
Setup for hardware tests.
void beep () const
Make a beep.
void readEOLsensors ()
Read the End of Line sensors.
void readEncoders () const
Read the Hall sensors that determine which carriage is in use.
void autoRead ()
Read both carriage sensors and End of Line sensors.
void autoTestEven () const
Set even-numbered solenoids.
void autoTestOdd () const
Set odd-numbered solenoids.
void handleTimerEvent ()
Timer event every 500ms to handle auto functions.
Private Attributes
bool m_autoReadOn = false
bool m_autoTestOn = false
unsigned long m_lastTime = 0U
bool m_timerEventOdd = false
char buf [BUFFER_LEN] = {0}
Member Function Documentation
autoReadCmd()
void Tester::autoReadCmd () final virtual
Auto read command handler.
Implements TesterInterface.
autoTestCmd()
void Tester::autoTestCmd () final virtual
Auto test command handler.
Implements TesterInterface.
beepCmd()
void Tester::beepCmd () final virtual
Beep command handler.
Implements TesterInterface.
References beep().
encoderChange()
void Tester::encoderChange () final virtual
Interrupt service routine for encoder A.
Reimplemented from TesterInterface.
helpCmd()
void Tester::helpCmd () final virtual
Help command handler.
Implements TesterInterface.
loop()
void Tester::loop () final virtual
Main loop for hardware tests.
Implements TesterInterface.
References handleTimerEvent().
quitCmd()
void Tester::quitCmd () final virtual
Quit command handler.
Implements TesterInterface.
readEncodersCmd()
void Tester::readEncodersCmd () final virtual
Read encoders command handler.
Implements TesterInterface.
References readEncoders().
readEOLsensorsCmd()
void Tester::readEOLsensorsCmd () final virtual
Read EOL sensors command handler.
Implements TesterInterface.
References readEOLsensors().
sendCmd()
void Tester::sendCmd () final virtual
Send command handler.
Implements TesterInterface.
setAllCmd()
void Tester::setAllCmd (const uint8_t * buffer, size_t size) final virtual
Set all solenoids command handler.
Parameters
buffer Pointer to a data buffer.
size Number of bytes of data in the buffer.
Implements TesterInterface.
setSingleCmd()
void Tester::setSingleCmd (const uint8_t * buffer, size_t size) final virtual
Set single solenoid command handler.
Parameters
buffer Pointer to a data buffer.
size Number of bytes of data in the buffer.
Implements TesterInterface.
startTest()
Err_t Tester::startTest (Machine_t machineType) final virtual
Start hardware test.
Parameters
machineType Machine type.
Returns
Error code (0 = success, other values = error).
Implements TesterInterface.
References setUp().
stopCmd()
void Tester::stopCmd () final virtual
Stop command handler.
Implements TesterInterface.
The documentation for this class was generated from the following files:
src/ayab/tester.h
src/ayab/tester.cpp
test/mocks/tester_mock.cpp