AYAB Arduino Firmware: Beeper Class Reference
Beeper Class Reference
Class to actuate a beeper connected to PIEZO_PIN.
#include <beeper.h>
Public Member Functions
void init (bool enabled) final
bool enabled () final
BeepState getState () final
void ready () final
void finishedLine () final
void endWork () final
void schedule () final
Private Member Functions
void beep (uint8_t repeats)
Private Attributes
BeepState m_currentState
BeepState m_nextState
unsigned long m_nextTime
uint8_t m_repeat
bool m_enabled
Detailed Description
Class to actuate a beeper connected to PIEZO_PIN.
Member Function Documentation
beep()
void Beeper::beep (uint8_t repeats) private
Generic beep function.
/param repeats number of beeps
enabled()
bool Beeper::enabled () final virtual
Get beeper enabled flag
Implements BeeperInterface.
endWork()
void Beeper::endWork () final virtual
Beep to indicate the end the knitting pattern
Implements BeeperInterface.
References beep().
finishedLine()
void Beeper::finishedLine () final virtual
Beep to indicate the end of a line
Implements BeeperInterface.
References beep().
getState()
BeepState Beeper::getState () final virtual
Get beeper state
Implements BeeperInterface.
init()
void Beeper::init (bool enabled) final virtual
Initialize beeper
Implements BeeperInterface.
ready()
void Beeper::ready () final virtual
Beep to indicate readiness
Implements BeeperInterface.
References beep().
schedule()
void Beeper::schedule () final virtual
Beep handler scheduled from main loop
Implements BeeperInterface.
The documentation for this class was generated from the following files:
src/ayab/beeper.h
src/ayab/beeper.cpp
test/mocks/beeper_mock.cpp