name: Create Release
on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+", "v[0-9]+.[0-9]+.[0-9]+-[0-9a-zA-Z]+"]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Build Firmware
        uses: ./.github/workflows/build_firmware
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          commit: ${{ github.sha }}
          body: "" # release message, alternative to body_path
          # body_path: release_text.md  # uncomment if not used
          draft: ${{ startsWith(github.ref_name,'test')}}
          prerelease: false
          allowUpdates: true
          artifacts: build/*.hex
          replacesArtifacts: true
      - name: Deploy source code documentation to pages
        uses: DenverCoder1/doxygen-github-pages-action@v1.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: doc
          config_file: Doxyfile
