name: Sonar

on:
  workflow_run:
    workflows: [Build]
    types: [requested]

jobs:
  sonar:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    env:
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory
    steps:
    - name: Checkout repo and submodules
      uses: actions/checkout@v3
      with:
        repository: ${{ github.event.workflow_run.head_repository.full_name }}
        ref: ${{ github.event.workflow_run.head_branch }}
        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of sonar analysis
#    - name: 'Download code coverage'
#      uses: actions/github-script@v6
#      with:
#        script: |
#          let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#              run_id: context.payload.workflow_run.id,
#          });
#          let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
#              return artifact.name == "ayab-firmware-code-coverage"
#          })[0];
#          let download = await github.rest.actions.downloadArtifact({
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#              artifact_id: matchArtifact.id,
#              archive_format: 'zip',
#          });
#          let fs = require('fs');
#          fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/ayab-firmware-code-coverage.zip`, Buffer.from(download.data));
#    - name: 'Unzip code coverage'
#      run: unzip ayab-firmware-code-coverage.zip -d coverage
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.scm.revision=${{ github.event.workflow_run.head_sha }}
          -Dsonar.pullrequest.key=${{ github.event.workflow_run.pull_requests[0].number }}
          -Dsonar.pullrequest.branch=${{ github.event.workflow_run.pull_requests[0].head.ref }}
          -Dsonar.pullrequest.base=${{ github.event.workflow_run.pull_requests[0].base.ref }}
